// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	models "goshm/models"
)

// Caller is an autogenerated mock type for the Caller type
type Caller struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, httpClient, args
func (_m *Caller) Get(ctx context.Context, httpClient *http.Client, args models.FetchArgs) ([]models.CallResponse, error) {
	ret := _m.Called(ctx, httpClient, args)

	var r0 []models.CallResponse
	if rf, ok := ret.Get(0).(func(context.Context, *http.Client, models.FetchArgs) []models.CallResponse); ok {
		r0 = rf(ctx, httpClient, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CallResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *http.Client, models.FetchArgs) error); ok {
		r1 = rf(ctx, httpClient, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
