// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "goshm/models"

	mock "github.com/stretchr/testify/mock"
)

// Writer is an autogenerated mock type for the Writer type
type Writer struct {
	mock.Mock
}

// Generate provides a mock function with given fields: param, data
func (_m *Writer) Generate(param models.FetchArgs, data []models.CallResponse) error {
	ret := _m.Called(param, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.FetchArgs, []models.CallResponse) error); ok {
		r0 = rf(param, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFilename provides a mock function with given fields: param
func (_m *Writer) GetFilename(param models.FetchArgs) string {
	ret := _m.Called(param)

	var r0 string
	if rf, ok := ret.Get(0).(func(models.FetchArgs) string); ok {
		r0 = rf(param)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
